int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int i);
int _isalpha(int i);
int print_sign(int i);
int _abs(int);
int print_last_digit(int);
void jack_bauer(void);
int add(int, int);
void print_to_98(int i);
void times_table(void);
